# Uncomment the next line to define a global platform for your project
 platform :ios, ’10.2’

target 'GJDKWeather' do
  pod 'MobileCenter'
  pod 'MobileCenter/MobileCenterAnalytics'
  pod 'MobileCenter/MobileCenterCrashes'
end
